spring:
  application:
    name: poc-1-kafka-cadastro-pedido-ms-springboot

server:
  port: 8081

config:
  kafka:
    server-url: "http://localhost:29092"
    topics:
      pedidos-criados: 'poc1.pedidos-criados'